# Generated by Django 4.2.8 on 2023-12-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBoardIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('project_number', models.IntegerField(choices=[(1, 'Project 1'), (2, 'Project 2'), (3, 'Project 3')], default=0)),
                ('board_number', models.IntegerField(choices=[(1, 'Board 1'), (2, 'Board 2'), (3, 'Board 3')], default=0)),
            ],
        ),
    ]
