# Generated by Django 4.2.8 on 2023-12-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectboardissue',
            options={'verbose_name': 'SprintBoard Issue', 'verbose_name_plural': 'SprintBoard Issues'},
        ),
        migrations.RemoveField(
            model_name='projectboardissue',
            name='board_number',
        ),
        migrations.AddField(
            model_name='projectboardissue',
            name='issue_status',
            field=models.IntegerField(choices=[(1, '❌ Not Started ❌'), (2, '⏳ In Progress ⌛️'), (3, '✅ Complete ✅')], default=1),
        ),
        migrations.AlterField(
            model_name='projectboardissue',
            name='project_number',
            field=models.IntegerField(choices=[(1, 'Project 1'), (2, 'Project 2'), (3, 'Project 3')], default=1),
        ),
    ]
