# Generated by Django 4.2.8 on 2023-12-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectboard', '0003_alter_projectboardissue_issue_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboardissue',
            name='issue_status',
            field=models.CharField(choices=[('❌ Not Started ❌', '❌ Not Started ❌'), ('⏳ In Progress ⌛️', '⏳ In Progress ⌛️'), ('✅ Complete ✅', '✅ Complete ✅')], default='❌ Not Started ❌', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectboardissue',
            name='project_number',
            field=models.CharField(choices=[('Project 1', 'Project 1'), ('Project 2', 'Project 2'), ('Project 3', 'Project 3')], default='Project 1', max_length=200),
        ),
    ]
